name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Cargo Build
        run: cargo build --verbose
      - name: Cargo Test
        run: cargo test --verbose
      - name: Install semfora-engine
        run: cargo install semfora-engine --force
      - name: Semfora Validate
        run: semfora-engine validate .
